### ISSUE TITLE
TypeError: _version_compare_pad_0 is not a function

### ISSUE THREAD

**Issue by nimuxoha** [qsniyg/maxurl#1033]
Seems Image Max URL (latest version from GH: userscript.user.js) doesn't work as well with Violentmonkey beta v2.13.0.18
It's still working with 2.13.0

```
Image Max URL.user.js:105933 TypeError: _version_compare_pad_0 is not a function
    at version_compare (Image Max URL.user.js:17232:4)
    at Image Max URL.user.js:1556:49
    at Image Max URL.user.js:105931:3
    at window.VMinbhgcrgde2q3crawh (Image Max URL.user.js:105933:3)
    at i (injected-web.js:1:16441)
    at Rt (injected-web.js:1:16553)
    at set (injected-web.js:1:16282)
    at Image Max URL.user.js:1:28
window.VMinbhgcrgde2q3crawh @ Image Max URL.user.js:105933
```

Browser:
Google Chrome 102.0.5005.22

**Comment by nimuxoha** [comment]
Seems related to the changes in [v2.13.0.11](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.11)
After a quick test seems to work fine with [v2.13.0.10](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.10)

**Comment by qsniyg** [comment]
Closing as https://github.com/qsniyg/maxurl/issues/1037 (duplicate) reports it to be fixed. If it doesn't work however, please let me know.
